### ISSUE TITLE
error: failed to run custom build command for `hbb_common v0.1.0 (E:\rustdesk\rustdesk\agent_src\libs\hbb_common)`

### ISSUE THREAD

**Issue by qq281833259** [YDHCUI/rustdesk#10]
![image](https://github.com/user-attachments/assets/f9173ed4-886e-49ac-8bdd-64ab78a0d35a)
 
大佬这个如何解决 查了好久都没有找到对应文献

**Comment by YDHCUI** [comment]
看着像是ipc库的版本不对 你去原作者那里找到对应的版本放到本地试试

**Comment by qq281833259** [comment]
太感谢了，这个报错已经跳过了 但出现了新的错误信息 
![614f8048312352551a86ce145a1e0f8](https://github.com/user-attachments/assets/007cd5fc-8801-4f05-a74b-e4baeb6d3beb)
这对于rust初学者太困扰了

**Comment by YDHCUI** [comment]
需要装clang然后配置环境变量 还要装vcpkg这些

**Comment by qq281833259** [comment]
![image](https://github.com/user-attachments/assets/09b96065-7fc7-4f33-bb3e-e9a9498b8ebc)
非常遗憾，我能够编译官方的rustdesk 可您这边的 我还是编译不了 报错如上，能告诉我如何解决它吗  我已经替换了官方的\libs\scrap 和\libs\hbb_common 文件 但依旧无法编译

**Comment by Xusir123456** [comment]
我跟你是一样的问题，请问你后面解决了吗
