### ISSUE TITLE
第二次访问失败

### ISSUE THREAD

**Issue by wsgehaishan520** [YDHCUI/rustdesk#4]
第一次连接成功后，关闭，再进行第二会提示：远程电脑不在线！我是用自定义服务器

**Comment by wsgehaishan520** [comment]
并且固定了连接的用户名(id)

**Comment by YDHCUI** [comment]
我本地用官方服务器试的没有问题， 会不会是你的id太短冲突了  用一个长点的id试试？

**Comment by YDHCUI** [comment]
我本地用官方服务器试的没有问题，&nbsp;会不会是你的id太短冲突了&nbsp; 用一个长点的id试试？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 凌晨4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [YDHCUI/rustdesk] 第二次访问失败 (Issue #4)





 
并且固定了连接的用户名(id)
 
&mdash;

**Comment by YDHCUI** [comment]
我懂你的意思了  因为官方的server 是有做了id和ip映射的 所以你agent断开后需要起一个新的id才能使用。
如果想固定id的 又经脉重复使用的话 可以用我这个精简版的server

**Comment by wsgehaishan520** [comment]
好的，非常感谢你的解答。我想问下，怎么设置server在ubuntu里自启，和agent在windows下自启呢

**Comment by wsgehaishan520** [comment]
server 我用pm2启动了起来了，但是windows不知道 是安装服务还是注册表启动

**Comment by wsgehaishan520** [comment]
还有一发现一个问题，为何用你的server连接成功后，延迟很大呢，局域网也是。但是用官方客户端连接的就正常

**Comment by YDHCUI** [comment]
原版里面是没有这个功能的，自己改的话 可以在这里面加一个控制选项。
![image](https://user-images.githubusercontent.com/46884495/225819265-c320f4dd-6106-4d79-82b2-437c628e4332.png)

**Comment by wsgehaishan520** [comment]
3Q
