### ISSUE TITLE
前辈，您好！请协助。

### ISSUE THREAD

**Issue by tyab00** [YDHCUI/rustdesk#6]
前辈，您好！在被远程的机器上执行server -i xx.xx.xx.xx，提示“server不是内部或外部命令”？内网之间能互访吗?通过IP地址。
前辈，您辛苦付出！咱们有偿服务可以码？我的邮箱地址：tyab@163.com，微信：tyab00。很高兴认识您！

**Comment by YDHCUI** [comment]
server是服务端    被控端运行agent

**Comment by tyab00** [comment]
前辈，这个服务端是在windows上运行的吗？是用这个server替代rustdesk编译好的server吗？
谢谢你的回复。
















在 2023-11-14 10:18:19，"道长且阻" ***@***.***> 写道：

server是服务端 被控端运行agent
